### PR TITLE
Wrote module to scrape the files.

### PR DESCRIPTION
**Pull request by edwin-vallecillo**
@jravesloot Please review.

### CODE REVIEW

**Review by jravesloot — CHANGES_REQUESTED** [review]
Please check for old comments and debug statements and remove or edit where necessary.

Please also lint the code before resubmitting.  Thanks

**Comment by edwin-vallecillo** [comment]
Review changes @jravesloot

**Review by jravesloot — CHANGES_REQUESTED** [review]
@edwin-vallecillo Please normalize the spelling of 'competitiveness', and then we'll be good to go!

**Comment by jravesloot** [comment]
LGTM 👍

**Pull request merged**
